config/routes.rb
Rails.application.routes.draw do
  # register and login
  get 'register', to: 'register#new'
  post 'register/create', to: 'register#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  # forget password and reset password
  get 'forget-password', to: 'forget_password#forgetPassword'
  post 'forget-password', to: 'forget_password#forgetPasswordEmail'
  get 'reset-password/:id', to: 'forget_password#new'
  put 'reset-password/:id', to: 'forget_password#resetPassword', as: 'passwordReset'

  # post and user csv export/import
  get 'posts/export', to: 'posts#export'
  get 'users/export', to: 'users#export'
  post 'posts/import', to: 'posts#import'
  post 'users/import', to: 'users#import'

  # user profile
  get 'profile', to: 'users#profile',  as: 'profile'

  # post, category and user crud
  resources :categories
  resources :posts
  resources :users

  # dashboard
  get '/dashboard', to: 'dashboard#index'
  get '/dashboard/user-chart', to: 'dashboard#userChart',  as: 'userChart'
  get '/dashboard/post-chart', to: 'dashboard#postChart',  as: 'postChart'

  # landing
  get '/', to: 'landing#index'
  get '/blogs', to: 'landing#blog'
  get '/category/:id/posts', to: 'landing#categoryPosts', as: 'categoryPosts'
  get '/post/:id', to: 'landing#postDetail', as: 'postDetail'
end

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <!-- admin css, js -->
  <%= stylesheet_link_tag 'admin/admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>

  <title>Bulletin Board SCM (Rails)</title>

  <!-- Google Font: Source Sans Pro -->
  <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->

  <!-- IonIcons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

   <!-- jquery, popper js, bootstrap js -->
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
     <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link font-bold" data-toggle="dropdown" href="#">
          <span><i class="fa fa-language mx-2"></i>
            <% if I18n.locale == :jp %>
              <%= t('japanese') %>
            <% else %>
              English
            <% end %>
          </span>
        </a>
        <div class="dropdown-menu dropdown-menu-sm dropdown-menu-left">
          <%= link_to "English", { :locale=>'en' }, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to t('japanese'), { :locale=>'jp' }, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto ">
      <% if logged_in? %>
       <!-- Messages Dropdown Menu -->
       <li class="nav-item dropdown">
        <a class="nav-link font-bold" data-toggle="dropdown" href="#">
          <span><%= authUser.name %><i class="fa fa-user px-2"></i></span>
        </a>
        <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
          <%= link_to t('profile'), profile_path(), class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to t('home'), '/', class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= button_to t('logout'), '/logout', method: :post, class: "dropdown-item" %>
        </div>
      </li>
      <% end %>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Project Name -->
    <a href="/dashboard" class="brand-link">
      <span class="brand-text font-weight-light">Bulletin Board SCM</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <% if isAdmin? %>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/users"><i class="fa fa-users"></i> <%= t('users') %></a>
            </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link" href="/categories"><i class="fa fa-table"></i> <%= t('categories') %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/posts"><i class="fa fa-sticky-note"></i> <%= t('posts') %></a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid py-4">
        <%= yield %>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2021-2022 <a href="#">SCM Bulletin Board</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>
</div>
</body>
</html>