config/routes.rb
Rails.application.routes.draw do
  # register and login
  get 'register', to: 'register#new'
  post 'register/create', to: 'register#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  # forget password and reset password
  get 'forget-password', to: 'forget_password#forgetPassword'
  post 'forget-password', to: 'forget_password#forgetPasswordEmail'
  get 'reset-password/:id', to: 'forget_password#new'
  put 'reset-password/:id', to: 'forget_password#resetPassword', as: 'passwordReset'

  # post and user csv export/import
  get 'posts/export', to: 'posts#export'
  get 'users/export', to: 'users#export'
  post 'posts/import', to: 'posts#import'
  post 'users/import', to: 'users#import'

  # user profile
  get 'profile', to: 'users#profile',  as: 'profile'

  # post, category and user crud
  resources :categories
  resources :posts
  resources :users

  # dashboard
  get '/dashboard', to: 'dashboard#index'
  get '/dashboard/user-chart', to: 'dashboard#userChart',  as: 'userChart'
  get '/dashboard/post-chart', to: 'dashboard#postChart',  as: 'postChart'

  # landing
  get '/', to: 'landing#index'
  get '/blogs', to: 'landing#blog'
  get '/category/:id/posts', to: 'landing#categoryPosts', as: 'categoryPosts'
  get '/post/:id', to: 'landing#postDetail', as: 'postDetail'
end

app/models/category.rb
class Category < ApplicationRecord
    # validation
    validates :name, presence: true

    # one to many with posts
    has_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'admin/admin'
  before_action :authorized

  # category list
  def index
    @categories = CategoriesService.categoryList
  end

  # new category form
  def new
    @category = Category.new
  end

  # create category
  def create
    @category = CategoriesService.createCategory(category_params)
    if @category.save
      flash[:notice] = "Category successfully created"
      redirect_to '/categories'
    else
      render :new
    end
  end

  # edit category form
  def edit
    @category = CategoriesService.editCategory(params[:id])
  end

  # update category
  def update
    @category = CategoriesService.updateCategory(params[:id], category_params)
    if @category.update(category_params)
      flash[:notice] = "Category successfully updated"
      redirect_to '/categories'
    else
      render :new
    end
  end

  # category detail
  def show
    @category = CategoriesService.categoryDetail(params[:id])
  end

  # delete category
  def destroy
    isDeleteCategory = CategoriesService.destroyCategory(params[:id])
    if isDeleteCategory
      flash[:notice] = "Category successfully deleted"
      redirect_to '/categories'
    else
      render :delete
    end
  end

  private

  # parameters from request
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_form.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0"><%= formTitle %></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Category</li>
        </ol>
      </div><!-- /.col -->
    </div>
  </div>
</div>
<hr>
<div class="content mx-3">
  <div class="container-fluid py-4">
    <%= form_with model: @category do |form| %>
      <div class="form-group row">
      <div class="col-md-2"> <%= form.label :name %> </div>
        <div class="col-md-6"><%= form.text_field :name ,class: "form-control" %></div>
          <% if @category.errors.any? %>
            <ul>
              <% @category.errors.full_messages_for(:name).each do |message| %>
                <li class="text-danger"><%= message %></li>
              <% end %>
            </ul>
          <% end %>
      </div>
      <br/>
      <div class="row">
        <div class="col-md-8">
          <div class="row justify-content-center">
            <%= form.submit submitBtn, class: "btn btn-primary mx-2" %>
            <%= link_to t('back'), categories_path, class: "btn btn-secondary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render "form", category: @category, formTitle: "Update Category", submitBtn: t('update') %>

app/views/categories/index.html.erb
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Category List</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Category</li>
          </ol>
        </div><!-- /.col -->
      </div>
    </div>
  </div>
  <div class="content mx-3">
    <div class="container-fluid py-4">
      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong><%= flash[:notice] %></strong>
        </div>
      <% end %>
      <div class="row justify-content-between pb-3 pl-2">
        <div class="col-md-4">
          <%= link_to "New category", new_category_path, class: "btn btn-outline-success" %>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Category Name</th>
                    <th>Created Date</th>
                    <th collapse=2>Operation</th>
                </tr>
            </thead>
            <tbody>
                <% @categories.each do |category| %>
                <tr>
                    <td><%= link_to category.name, category %></td>
                    <td><%= category.created_at.strftime('%b %d, %Y') %></td>
                    <td>
                      <%= link_to t('edit'), edit_category_path(category), 
                                      class: "btn btn-info" %>
                      <%= link_to t('delete'), category_path(category),
                                      method: :delete,
                                      data: { confirm: "Are you sure?" }, 
                                      class: "btn btn-danger" %></td>
                 
                </tr>
                <%end%>
            </tbody>
        </table>
      </div>
    </div>
  </div>
  

app/views/categories/new.html.erb
<%= render "form", category: @category, formTitle: "Create Category", submitBtn: t('create') %>

app/views/categories/show.html.erb
<div class="card">
    <div class="card-header">
      Category Details
      <%= link_to "Back", categories_path, class: "btn btn-secondary float-right" %>
    </div>
    <div class="card-body">
      <div class="form-group row">
          <label for="name" class="col-sm-2 col-form-label">Name</label>
          <div class="col-sm-10">
              <span for="name" class="col-sm-10 col-form-label"><%= @category.name %></span>
          </div>
      </div>
      <div class="form-group row">
          <label for="posts" class="col-sm-2 col-form-label">Category's Posts</label>
          <div class="col-sm-10">
              <% @category.posts.each do |post| %>
                  <span for="title" class="col-sm-10 col-form-label"><%= post.title %></span><br>
              <% end %>
          </div>
      </div>
    </div>
  </div>